k3s_cluster:
  children:
    servers:
      hosts:
        k3s-s1.local:
          ansible_host: 192.168.5.21
          ansible_user: poe
          ansible_ssh_pass: MCMega2005!
        k3s-s2.local:
          ansible_host: 192.168.5.22
          ansible_user: poe
          ansible_ssh_pass: MCMega2005!
        k3s-s3.local:
          ansible_host: 192.168.5.23
          ansible_user: poe
          ansible_ssh_pass: MCMega2005!
    agents:
      hosts:
        k3s-a1.local:
          ansible_host: 192.168.5.24
          ansible_user: poe
          ansible_ssh_pass: MCMega2005!
        k3s-a2.local:
          ansible_host: 192.168.5.25
          ansible_user: poe
          ansible_ssh_pass: MCMega2005!
        k3s-a3.local:
          ansible_host: 192.168.5.26
          ansible_user: poe
          ansible_ssh_pass: MCMega2005!
        k3s-a4.local:
          ansible_host: 192.168.5.27
          ansible_user: poe
          ansible_ssh_pass: MCMega2005!
        k3s-a5.local:
          ansible_host: 192.168.5.28
          ansible_user: poe
          ansible_ssh_pass: MCMega2005!
        k3s-a6.local:
          ansible_host: 192.168.5.29
          ansible_user: poe
          ansible_ssh_pass: MCMega2005!